apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: sean-face-scan-server
  annotations:
    scenarios.ai.sap.com/description: "Face recognition backend server"
    scenarios.ai.sap.com/name: "sean-face-scan-server"
    executables.ai.sap.com/description: "Face recognition backend server"
    executables.ai.sap.com/name: "sean-face-scan-server"
  labels:
    scenarios.ai.sap.com/id: "sean-face-scan-server"
    ai.sap.com/version: "0.1.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
        - name: sean-personal-dockerhub
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/seanxjtan/fastapi:initial
          ports:
            - containerPort: 9001
              protocol: TCP
