apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: facescanforthtry
  annotations:
    scenarios.ai.sap.com/description: "Face recognition backend server 4th try"
    scenarios.ai.sap.com/name: "sean-face-scan-server-4th"
    executables.ai.sap.com/description: "Face recognition backend server forth try"
    executables.ai.sap.com/name: "sean-face-scan-server-4th"
  labels:
    scenarios.ai.sap.com/id: "sean-face-scan-server-4th"
    ai.sap.com/version: "1.5"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        imagePullSecrets:
        - name: credstutorialrepo # your docker registry secret
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/chewkxmy/facescan:05
          workingDir: /app
          ports:
            - containerPort: 9001
              protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              uvicorn app.src.face_api:app --host 0.0.0.0 --port 9001
          env:
            - name: HOME
              value: "/app"